example_app/__init__.py
#!/bin/python3
from flask import Flask
import os
from dotenv import load_dotenv
import logging

# I find it helpful to define the root path of the app here
# You can use this to assign relative paths for file routing / .env loading / etc.
here = os.path.abspath(os.path.dirname(__file__))

# Path to .env file
env_path = os.path.join(here, ".env")

# Validate - if the path is valid we'll load the .env to use
if not os.path.exists(env_path):
    raise OSError("Whoa there! Looks like we're missing a .env file Cowboy")
else:
    load_dotenv(env_path)

# Setup logger
logging.basicConfig(level=logging.INFO)

##########


def create_app():
    """
    This helper function creates the Flask app. It is
    imported by the wsgi.py in the project root directory
    where it can be run on a server
    """

    # Instantiate the app ... __name__ indicates that the app
    # will be called "example_app"
    app = Flask(__name__)
    app.secret_key = os.environ.get("SECRET_KEY")

    # No prefix example
    from example_app.route_one import bp as no_prefix_bp

    app.register_blueprint(no_prefix_bp)

    # URL prefix example
    from example_app.route_two import bp as with_prefix_bp

    app.register_blueprint(with_prefix_bp, url_prefix="/nba")

    ###

    # Tell the user that we're running
    logging.info(" === App Running ===")

    return app

example_app/route_one/__init__.py
from flask import Blueprint

bp = Blueprint("route_one", __name__)

from example_app.route_one import routes

example_app/route_one/routes.py
#!/bin/python3
from flask import render_template, redirect, url_for, request
from dotenv import load_dotenv
import random
import logging

from example_app import env_path
from example_app.route_one import bp
from example_app.utilities.utils import flash_a_message

load_dotenv(env_path)
logging.basicConfig(level=logging.INFO)

##########


@bp.route("/", methods=["GET", "POST"])
@bp.route("/home_route", methods=["GET", "POST"])
def index():
    """
    LANDING PAGE

    This route renders the index.html file, which we're using
    as landing page
    """

    logging.info("Hit the landing route!")

    """
    When we send a POST request, we're telling the Flask app that we
    want a function to trigger. In this case we want to trigger the
    flash_a_message() function and then redirect back to the index (the same
    route that we're writing this code in)

    Run the app and watch the output - you'll see a POST request followed immediately
    by a GET request for 
    """

    if request.method == "POST":
        flash_a_message()

        name = random.choice(["Patrick", "Jeremy", "Robb", "Leo", "Joan", "Jose"])

        return redirect(url_for("route_one.interactive_route", name=name))

    return render_template("index.html")


@bp.route("/state_flags", methods=["GET", "POST"])
def example_route():

    logging.info("Hit the state flag route!")

    state_flags = {
        "California": "https://cdn.britannica.com/46/7046-004-BB1F8E32/state-flag-Bear-Flag-California-red-star-July-9-1846.jpg",
        "New York": "https://cdn.britannica.com/14/3014-004-BD154711/flag-New-York-color-uniforms-facings-American-1909.jpg",
        "Virginia": "https://cdn.britannica.com/40/4940-004-63FAF073/Flag-Virginia.jpg",
        "North Carolina": "https://cdn.britannica.com/85/3085-004-29C93A89/design-independence-Union-flag-convention-state-North-April-12-1776.jpg",
        "Pennsylvania": "https://cdn.britannica.com/29/3429-004-4A64B1C5/Pennsylvania-state-flag-William-Penn-blue-coat-1777.jpg",
    }

    state = random.choice([x for x in state_flags.keys()])

    return render_template(
        "route_one.html", state_name=state, flag_image=state_flags[state]
    )


@bp.route("/interactive/<name>", methods=["GET", "POST"])
def interactive_route(name: str):
    return render_template("interactive.html", name=name)

example_app/route_two/__init__.py
from flask import Blueprint

bp = Blueprint("route_two", __name__)

from example_app.route_two import routes

example_app/route_two/routes.py
#!/bin/python3
from flask import render_template
from dotenv import load_dotenv
import random
import logging

from example_app import env_path
from example_app.route_two import bp

load_dotenv(env_path)
logging.basicConfig(level=logging.INFO)

##########


@bp.route("/90s_legends", methods=["GET", "POST"])
def another_good_example():
    """
    90S LEGENDS ROUTE

    When this route is registered by Flask we're going to attach a URL prefix to it.
    Run the app and note the URL when you hit this route, you should see a leading "/nba"
    """

    logging.info("Hit the 90s legends route!")

    # Dictionary of values for each NBA player
    superstars = {
        "Patrick Ewing": {
            "image_source": "https://www.si.com/.image/ar_1:1%2Cc_fill%2Ccs_srgb%2Cfl_progressive%2Cg_xy_center%2Cq_auto:good%2Cw_1200%2Cx_2189%2Cy_649/MTg5NzA2ODExMTE1MzE2NDIx/usatsi_8742383.jpg",
            "team": "New York Knicks",
        },
        "Michael Jordan": {
            "image_source": "https://www.nbcsports.com/sites/rsnunited/files/styles/responsive_background_mobile/public/archive/assets_media_gallery/chicago/2020/05/21/jordan_thumb-1.jpg",
            "team": "Chicago Bulls",
        },
        "Charles Barkley": {
            "image_source": "https://www.golfdigest.com/content/dam/images/golfdigest/fullset/2021/1/CharlesBarkley_PhoenixSuns.jpg",
            "team": "Phoenix Suns",
        },
        "Penny Hardaway": {
            "image_source": "https://cdn.vox-cdn.com/thumbor/2Fisw2vKlnhqjb5BSZ1Ns15G650=/0x0:2430x3600/1200x800/filters:focal(974x1158:1362x1546)/cdn.vox-cdn.com/uploads/chorus_image/image/69511386/903568036.0.jpg",
            "team": "Orlando Magic",
        },
        "Kareem Abdul-Jabar": {
            "image_source": "https://i.ebayimg.com/images/g/4vgAAOSwv7BdFDVb/s-l500.jpg",
            "team": "Los Angeles Lakers",
        },
    }

    # Randomly pick a key from the dictionary
    key = random.choice([x for x in superstars.keys()])

    # Access the values for the selected player
    star = superstars[key]

    """
    Here we're going to pass values to the HTML, which we will render with Jinja

    Take a look at "templates/route_two.html" and look at how the logic is folded
    in with {{ }} braces
    """

    logging.info(f"Rendering {key}'s information...")

    return render_template(
        "route_two.html",
        image=star["image_source"],
        team=star["team"],
        full_name=key,
        first_name=key.split(" ")[0],
    )

example_app/templates/base.html
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Favicon -->
    <link rel="icon" type="icon/png" href="{{ url_for('static', filename='images/noggin.png') }}">

    <!--- Bootstrap CSS --->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
        integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>

    <!-- Custom CSS-->
    <link rel="stylesheet" href="{{ url_for('static', filename='main.css') }}">
    {% block styles %}
    {% endblock %}

    <title>
        {% block title %}
        {% if title %}
        {{ title }} -
        {% else %}
        An Excellent Flask Tutorial
        {% endif %}
        {% endblock %}
    </title>
</head>

<body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{{ url_for('route_one.index') }}" style="font-size: 185%;">
            A Very Fun Flask Tutorial
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse ml-auto" id="navbarSupportedContent">
            <li class="nav-item">
                <a class="navbar-link" href="{{ url_for('route_one.example_route') }}">Route No. 1</a>
            </li>
            <li class="nav-item">
                <a class="navbar-link" href="{{ url_for('route_two.another_good_example') }}">Route No. 2</a>
            </li>
        </div>
    </nav>

    <!-- Flashed messages-->
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    {% for message in messages %}
    <div class='alert alert-info' role='alert'>{{ message }}</div>
    {% endfor %}
    {% endif %}
    {% endwith %}

    <!-- Custom content -->
    {% block content %}
    {% endblock %}

    <!-- Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
        integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
        integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
        crossorigin="anonymous"></script>

    <!-- Custom scripts -->
    {% block scripts %}
    {% endblock %}
</body>

</html>

example_app/templates/index.html
<html>
{% extends "base.html" %}

<body>
    {% block content %}
    <div class="main_container">
        <h1>Howdy!</h1>
    </div>
    <div class="main_container">
        <form action="{{ url_for('route_one.index') }}" method="POST">
            <button class="btn btn-primary" type="submit">Say Something Nice</button>
        </form>
    </div>
    {% endblock %}
</body>

</html>

example_app/templates/interactive.html
<html>
{% extends 'base.html' %}

<body>
    {% block content %}
    <h1>Hi {{ name }}!</h1>
    {% endblock %}
</body>

</html>

example_app/templates/route_one.html
<html>
{% extends "base.html" %}

<body>
    {% block content %}
    <div class="main_container">
        <h1>State Flag Route</h1>
    </div>
    <div class="main_container">
        <h3>This is the <b>{{ state_name }}</b> state flag</h3>
        <img src="{{ flag_image }}" width="60%">
    </div>
    {% endblock %}
</body>

</html>

example_app/templates/route_two.html
<html>
{% extends "base.html" %}

<body>
    {% block content %}
    <div class="main_container">
        <h1>90's Superstars</h1>
    </div>
    {% if first_name != "Kareem" %}
    <div class="main_container">
        <h2>This is {{ full_name }}</h2>
        <h4>
            {{ first_name }} played for the <b>{{ team }}</b>
        </h4>
        <img src="{{ image }}" width="65%">
    </div>
    {% else %}
    <div class="main_container">
        <h2>This is {{ full_name }}</h2>
        <h4>
            {{ first_name }} <b>DID NOT</b> play for the {{ team }} in the 1990's
        </h4>
        <img src="{{ image }}" width="65%">
    </div>
    {% endif %}
    {% endblock %}
</body>

</html>